default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: postgres
  password: postgres


development:
  <<: *default
  database: sellfast_development

test:
  <<: *default
  database: sellfast_test

production:
  <<: *default
  database: sellfast_production
